targets:
  $default:
    builders:
      NGWF:htmlcssBuilder:
        generate_for:
          - lib/app/**.html
          - lib/app/**.css
      sass_builder:
        release_options:
          outputStyle: compressed
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
        dev_options:
          dart2js_args:
          - --no-minify
          # - echo "server run"
        release_options:
          dart2js_args:
          - --minify
          - -O4
          - --no-source-maps 