name: NGWF
description: Super-Puper-Mega-Web-Framework (Angular mini-clone).
version: 0.0.1
#homepage: https://www.example.com

scripts:
  serve:
    - echo "server run"
    - webdev serve --auto restart
  build:
    - rd /S /Q build
    - dart  html2dart.dart
    - webdev build
    - terser build/main.dart.js -c toplevel -m --safari10 --ie8 -f wrap_func_args  -o build/main.dart.js
    - echo "Build completed"

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  sass_builder:
