name: NGWFSPA
description: testSPA with NGWF
version: 0.0.1
#homepage: https://www.example.com

scripts:
  serve:
    - echo "server run"
    - webdev serve -n unsound -- --delete-conflicting-outputs
  build:
    - webdev build -n unsound -- --delete-conflicting-outputs
    # - terser build/main.dart.js -c toplevel -m --safari10 --ie8 -f wrap_func_args  -o build/main.dart.js
    - echo "Build completed"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  NGWF:
    path: ./pkg/NGWF
#  path: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  pedantic: ^1.9.0
  sass_builder:
  NGWF:
    path: ./pkg/NGWF