name: NGWF
description: Super-Puper-Mega-Web-Framework (Angular mini-clone).
version: 0.0.1
#homepage: https://www.example.com



environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build:

# dev_dependencies:
#   build: